version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 32700:5432
    volumes:
     - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ee_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ee_db

volumes:
  postgres_data: